In [1]:
import csv
import json
import pandas as pd

In [2]:
# Files to load
symptom_data_to_load = "Resources/CleanedDataSymptoms.csv"
lifestyle_data_to_load = "Resources/CleanedData.csv"

In [3]:
all_data_df = pd.read_csv(symptom_data_to_load)
all_data_df.head()

,Unnamed: 0,Patient Id,Age,Gender,Air Pollution,Alcohol use,Dust Allergy,OccuPational Hazards,Genetic Risk,chronic Lung Disease,...,Fatigue,Weight Loss,Shortness of Breath,Wheezing,Swallowing Difficulty,Clubbing of Finger Nails,Frequent Cold,Dry Cough,Snoring,Cancer Severity
0,0,P1,33,1,2,4,5,4,3,2,...,3,4,2,2,3,1,2,3,4,1
1,1,P10,17,1,3,1,5,3,4,2,...,1,3,7,8,6,2,1,7,2,2
2,2,P100,35,1,4,5,6,5,5,4,...,8,7,9,2,1,4,6,7,2,3
3,3,P1000,37,1,7,7,7,7,6,7,...,4,2,3,1,4,5,6,7,5,3
4,4,P101,46,1,6,8,7,7,7,6,...,3,2,4,1,4,2,4,2,3,3

In [4]:
lifestyle_data_df = pd.read_csv(lifestyle_data_to_load)
lifestyle_data_df.head()

,Unnamed: 0,Patient Id,Age,Gender,Air Pollution,Alcohol use,Dust Allergy,OccuPational Hazards,Genetic Risk,chronic Lung Disease,Balanced Diet,Obesity,Smoking,Passive Smoker,Cancer Severity
0,0,P1,33,1,2,4,5,4,3,2,2,4,3,2,1
1,1,P10,17,1,3,1,5,3,4,2,2,2,2,4,2
2,2,P100,35,1,4,5,6,5,5,4,6,7,2,3,3
3,3,P1000,37,1,7,7,7,7,6,7,7,7,7,7,3
4,4,P101,46,1,6,8,7,7,7,6,7,7,8,7,3

In [5]:
#drop unnamed columns from both files 
all_data_df.drop('Unnamed: 0', inplace=True, axis=1)
all_data_df.head()

,Patient Id,Age,Gender,Air Pollution,Alcohol use,Dust Allergy,OccuPational Hazards,Genetic Risk,chronic Lung Disease,Balanced Diet,...,Fatigue,Weight Loss,Shortness of Breath,Wheezing,Swallowing Difficulty,Clubbing of Finger Nails,Frequent Cold,Dry Cough,Snoring,Cancer Severity
0,P1,33,1,2,4,5,4,3,2,2,...,3,4,2,2,3,1,2,3,4,1
1,P10,17,1,3,1,5,3,4,2,2,...,1,3,7,8,6,2,1,7,2,2
2,P100,35,1,4,5,6,5,5,4,6,...,8,7,9,2,1,4,6,7,2,3
3,P1000,37,1,7,7,7,7,6,7,7,...,4,2,3,1,4,5,6,7,5,3
4,P101,46,1,6,8,7,7,7,6,7,...,3,2,4,1,4,2,4,2,3,3

In [6]:
lifestyle_data_df.drop('Unnamed: 0', inplace=True, axis=1)
lifestyle_data_df.head()

,Patient Id,Age,Gender,Air Pollution,Alcohol use,Dust Allergy,OccuPational Hazards,Genetic Risk,chronic Lung Disease,Balanced Diet,Obesity,Smoking,Passive Smoker,Cancer Severity
0,P1,33,1,2,4,5,4,3,2,2,4,3,2,1
1,P10,17,1,3,1,5,3,4,2,2,2,2,4,2
2,P100,35,1,4,5,6,5,5,4,6,7,2,3,3
3,P1000,37,1,7,7,7,7,6,7,7,7,7,7,3
4,P101,46,1,6,8,7,7,7,6,7,7,8,7,3

In [7]:
all_data_df.dtypes

Patient Id                  object
Age                          int64
Gender                       int64
Air Pollution                int64
Alcohol use                  int64
Dust Allergy                 int64
OccuPational Hazards         int64
Genetic Risk                 int64
chronic Lung Disease         int64
Balanced Diet                int64
Obesity                      int64
Smoking                      int64
Passive Smoker               int64
Chest Pain                   int64
Coughing of Blood            int64
Fatigue                      int64
Weight Loss                  int64
Shortness of Breath          int64
Wheezing                     int64
Swallowing Difficulty        int64
Clubbing of Finger Nails     int64
Frequent Cold                int64
Dry Cough                    int64
Snoring                      int64
Cancer Severity              int64
dtype: object